# Generated by Django 5.0.6 on 2024-06-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
