# Generated by Django 5.0.6 on 2024-06-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_student_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='create_at',
            field=models.DateTimeField(),
        ),
    ]
