# Generated by Django 5.0.6 on 2024-06-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_student_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('univercity', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('create', models.DateField()),
                ('update', models.DateField(auto_now=True)),
            ],
        ),
    ]
