# Generated by Django 5.0.6 on 2024-06-26 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='stafNotificatuion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('crated_at', models.DateTimeField()),
                ('staf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.staf')),
            ],
        ),
    ]
