# Generated by Django 5.0.6 on 2024-06-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_studentnotifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentnotifications',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
