# Generated by Django 5.0.6 on 2024-07-02 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_alter_studentnotifications_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stafleave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('create', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now_add=True)),
                ('staf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.staf')),
            ],
        ),
    ]
